### ISSUE TITLE
PHPCBF Breaks Syntax

### ISSUE THREAD

**Issue by XedinUnknown** [inpsyde/php-coding-standards#45] opened 2021-01-27 11:37 UTC
## The Problem
When running unit tests, I see over 30 errors saying that classes like `Translationmanager\Exception\UnexpectedEntityException` are not found. Further up in the output, I see raw PHP code for those classes, like so:

```php
.....E<?php# -*- coding: utf-8 -*-

namespace Translationmanager\Exception;

/**
 * Class InvalidPostException
 */
class UnexpectedEntityException extends EntityException
{
    /**
     * Create a new Exception for Unexpected Post Value Retrieved
     *
     * @param string $postType
     * @param string $message
     * @return UnexpectedEntityException
     */
    public static function forPostValue($postType, $message)
    {
        $message = $message ?: "Unexpected post value retrieved for post type {$postType}";

        return new self($message);
    }

    /**
     * Create a new Exception for Unexpected Term Value Retrieved
     *
     * @param mixed $value
     * @param string $message
     * @return UnexpectedEntityException
     */
    public static function forTermValue($value, $message)
    {
        $valueType = is_object($value) ? get_class($value) : gettype($value);
        $message = $message ?: "Unexpected term value retrieved. Should be WP_Term but got {$valueType}";

        return new self($message);
    }
}
```

## Possible Cause
The start of comment sequences `//` or `#` are too close to the opening PHP tag `<?php`. This makes the interpreter misinterpret the files included by autoloading as text instead of PHP.

## Suggested Solution
Amend the rules to include a space between the starting PHP tag and the encoding declaration comment.

## Specs
- PHP: 7.1;
- PHPUnit: 7.5.20;
- `inpsyde/php-coding-standards`: 38546e64d1f04fb69d7105bfe41ef9e46c6f8bfb.

**Comment by XedinUnknown** [comment] 2021-01-27 11:44
This only happens when there already was an encoding declaration on the same line as the opening PHP tag. See c10f79564643fa6e4af97df7114438638399dbec.

**Comment by XedinUnknown** [comment] 2021-01-27 11:50
Looks like it's one of `PSR12.Files.OpenTag.NotAlone` or `PSR12.Files.FileHeader.SpacingAfterBlock` that's doing this.

**Comment by XedinUnknown** [comment] 2021-01-27 11:55
It was `PSR12.Files.OpenTag.NotAlone`. Excluding this sniff results in the tag being alone, and a blank line between it and the comment.

**Comment by gmazzap** [comment] 2021-01-27 12:52
This looks like a bug in the upstream [PSR12 rule](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PSR12/Sniffs/Files/OpenTagSniff.php).

We could exclude the rule in our standard, but the rule itself is fine. The problem is the "fix" part that is problematic. Maybe we should send a PR to PHPCS...

**Comment by XedinUnknown** [comment] 2021-01-27 13:37
Yep, looks like a problem in PSR12. Sounds good!

**Comment by gmazzap** [comment] 2021-04-22 10:16
I'm closing this. We're receiving bugfixes release sfrom upstream PHPCS so we should get the fix if they do it. If the fix will be done in a major/minor, we will get that when we'll update... I think we need to keep PHPCS updated anyway.

**Closed by gmazzap** 2021-04-22 10:16 UTC
Labels: bug

**Comment by XedinUnknown** [comment] 2021-06-02 21:31
This is still present, FYI.
