### ISSUE TITLE
Return Type check is not valid

### ISSUE THREAD

**Issue by bueltge** [inpsyde/php-coding-standards#18] opened 2018-08-28 19:16 UTC
The Inpsyde sniff (https://github.com/inpsyde/php-coding-standards/blob/master/Inpsyde/Sniffs/CodeQuality/ReturnTypeDeclarationSniff.php#L175) for check id return type is existing works only for method, like

`public function get_media_strings(array $strings): array` and not for functions, without a property visibility.

However if it will fail if is a function, without class, only namespace usage, then will the sniff get an error message ' Return type is missing'.

`function get_media_strings(array $strings): array`

![bildschirmfoto-20180828211236-1920x1080](https://user-images.githubusercontent.com/133425/44745230-71f80300-ab07-11e8-9711-eb5988f8c9d8.png)

**Comment by widoz** [comment] 2018-10-04 21:51
@bueltge Have you tested with the latest package? I tried to create a function within a namespace but I don't get your same issue.

**Comment by bueltge** [comment] 2018-10-05 15:53
Yes, with the 0.13.3 in test.

**Comment by gmazzap** [comment] 2018-10-08 05:52
I tested it and cannot reproduce. Moreover, the automates unit tests for the styles have different plain functions with return type and the testes pass.

I think the isse might be caused by a version of PHPCS which is not compatible.

@bueltge can you use these config in the require-dev section of your `composer.json`:

```json
    "squizlabs/php_codesniffer":    "3.2.*",
    "inpsyde/php-coding-standards": "^0.14"
```

and the tests again after  a `composer update`?

**Comment by widoz** [comment] 2018-10-08 08:02
@gmazzap @bueltge Indeed I had a lot of problems with the latest version 3.3.x with third party sniffers. The latest one is with object-calisthenics that doesn't autoload correctly the dependecies.

Btw, I tested the issue reported by @bueltge using version 3.3.2 and I didn't get anything strange 🤔

**Comment by bueltge** [comment] 2018-10-14 18:27
For my issue works it with `"^0.13"`.

@gmazzap The version 0.14* is not testable for me, not possible to get this version because I mean we haven't a [tag](https://github.com/inpsyde/php-coding-standards/releases) for this version key.
```bash
  Problem 1
    - The requested package inpsyde/php-coding-standards ^0.14 exists as inpsyde/php-coding-standards[0.1.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.9.0, dev-issue-8, dev-master, 0.13.x-dev, dev-psr] but these are rejected by your constraint.
```

In my context we can close this issue, all is fine and works. Thanks at @gmazzap and @widoz for your help!

**Comment by gmazzap** [comment] 2018-10-15 09:58
Yes @bueltge by bad. v0.14 is not released. So let's just close this!

**Closed by gmazzap** 2018-10-15 09:58 UTC
Labels: bug
